int channel = 0;
int resolution = 8;
int duty = 200;
int freq = 2000;

int g4 = 392;
int c5 = 523;
int d5 = 587;
int e5 = 659;
int f5 = 698;
int g5 = 784;
int a5 = 880;
int b5 = 988;

int crotchet = 500;
int space = 10;

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  ledcSetup(channel, freq, resolution);
  ledcAttachPin(13, channel);

}

void loop() {
  // put your main code here, to run repeatedly:
  ledcWriteTone(channel, e5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, e5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, f5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, g5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, g5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, f5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, e5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, d5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, c5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, c5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, d5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, e5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, e5);
  delay(crotchet*1.5);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, d5);
  delay(crotchet*0.5);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, d5);
  delay(crotchet*2);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, e5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, e5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, f5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, g5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, g5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, f5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, e5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, d5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, c5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, c5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, d5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, e5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, d5);
  delay(crotchet*1.5);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, c5);
  delay(crotchet*0.5);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, c5);
  delay(crotchet*2);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, d5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, d5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, e5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, c5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, d5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, e5);
  delay(crotchet*0.5);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, f5);
  delay(crotchet*0.5);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, e5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, c5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, d5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, e5);
  delay(crotchet*0.5);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, f5);
  delay(crotchet*0.5);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, e5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, d5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, c5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, d5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, g4);
  delay(crotchet*2);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, e5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, e5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, f5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, g5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, g5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, f5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, e5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, d5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, c5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, c5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, d5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, e5);
  delay(crotchet);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, d5);
  //delay(crotchet*1.5);
  delay(crotchet*2);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, c5);
  //delay(crotchet*0.5);
  delay(crotchet*2);
  ledcWrite(channel, 0);
  delay(space);
  ledcWriteTone(channel, c5);
  //delay(crotchet*2);
  delay(crotchet*4  );
  ledcWrite(channel, 0);
  delay(10000);
}
